<a href="https://colab.research.google.com/github/tunde99/TUTORIALS/blob/main/PyTorchIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to PyTorch

In [3]:
# import dependencies
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [6]:
a = torch.randn((2,3,4))
a

tensor([[[-1.8821, -0.7765,  2.0242, -0.0865],
         [ 0.0981, -1.2150,  0.7312,  1.1718],
         [-0.0255, -1.0233, -0.5962, -1.0055]],

        [[-0.2106, -0.0075,  1.6734,  0.0103],
         [-0.7040, -0.1853, -0.9962, -0.8313],
         [-0.4610, -0.5601,  0.3956, -0.9823]]])

In [8]:
print(a[0])

tensor([[-1.8821, -0.7765,  2.0242, -0.0865],
        [ 0.0981, -1.2150,  0.7312,  1.1718],
        [-0.0255, -1.0233, -0.5962, -1.0055]])


In [9]:
p = torch.tensor([1,2,3])
q = torch.tensor([4,5,6])
r = p+q
print(r)

tensor([5, 7, 9])
